### ISSUE TITLE
gallery component does not support wxfile url

### ISSUE THREAD

**Issue by genru** [skyvow/wux#10]
gallery 组件采用background的形式来展示图片，而目前微信background 不支持 `wxfile://tmp_1432973527o6zAJs9mBPbqQXsTYTB65vWW18sU5cdb0c6f3ac57085fd7a0f027cd51fe5.jpg`这样的本地路径（这是iOS 10选区的本地图片的路径）。

**Comment by skyvow** [comment]
感谢支持，当时没考虑到 background 不支持本地图片的情况。

**Comment by genru** [comment]
@skyvow  在你的代码基础上改成Image 了。可以的话，我可以 pull 过来

**Comment by skyvow** [comment]
@genru 可以
