### ISSUE TITLE
gallery component back button in navigation bar make user confused.

### ISSUE THREAD

**Issue by genru** [skyvow/wux#11]
gallery 展现图片时候。顶部的返回按钮容易让人理解错误，从而造成误操作。
比如页面stack 是
```
A > B > Gallery
```
此时点击返回按钮，会返回到 A，而不是用户期望的 B。

**Comment by skyvow** [comment]
确实如此，因为没有办法去操作小程序的顶部返回按钮，其他方案可以新增一个页面传参数实现或者
使用 wx.previewImage。

**Comment by genru** [comment]
我很喜欢你的gallery，因为可以定义删除动作。我的解决方法是把背景设个透明度，暗示用户这是个图层。还是在页面 B。
不知道这样是不是可以避免这样的问题。

**Comment by skyvow** [comment]
@genru 很不错呀，可以一试
