### ISSUE TITLE
模版嵌套模版的话 数据咋传递呢

### ISSUE THREAD

**Issue by 455631680** [skyvow/wux#13]

**Comment by skyvow** [comment]
小程序不支持模板嵌套

**Comment by Aixtuz** [comment]
由于 模板 JS 并不执行，所以我是这么用的：
- 在第一层模板之外的 JS 中处理好需要的所有数据，全部传入第一层模板；
- 任意层传入模板的数据需要遵守：传入第 n 层模板的数据，必须包含第 n+1 层模板的数据；
- 以此类推，直至最后一层;
- 模板无法二次处理数据，因此传入的数据必须能直接使用（所有模板外一次性处理好）。

**若用法不对，欢迎指正。**
