### ISSUE TITLE
gallery预览图片的时候，显示黑色背景，没有图片，左右滑动屏幕，图片才出现

### ISSUE THREAD

**Issue by lvsjack** [skyvow/wux#14]
如题

**Comment by lvsjack** [comment]
在开发工具上测试一切正常，但是ios中出现上述问题，还没有测试安卓是否会出现这个问题。

**Comment by lvsjack** [comment]
> map、canvas、video、textarea 是由客户端创建的原生组件，原生组件的层级是最高的，所以页面中的其他组件无论设置 z-index 为多少，都无法盖在原生组件上。 原生组件暂时还无法放在 scroll-view 上，也无法对原生组件设置 css 动画。

会不会和上面这段内容有关系？

**Comment by skyvow** [comment]
是的

**Comment by lvsjack** [comment]
@skyvow  有什么解决办法没？下面那个删除按钮挺实用好用

**Comment by skyvow** [comment]
@lvsjack 可以跳转到一个新的页面，实现 gallery 预览图片
