### ISSUE TITLE
dialog组件出现点击穿透问题

### ISSUE THREAD

**Issue by pop1213** [skyvow/wux#16]
模拟器没问题，真机上如果页面中有input、textarea组件，弹出dialog会出现点击穿透的问题，placehodel的内容会悬浮到dialog上面
![mmexport1501771989538](https://user-images.githubusercontent.com/24694915/28928029-bda12c1a-789e-11e7-81b6-a6b7b1edc6cc.jpg)

**Comment by canyu9512** [comment]
同样有这个问题，有解决方法吗

**Comment by workttt** [comment]
微信小程序input、textarea组件本来就有这样问题
