### ISSUE TITLE
跟weui一起使用，会样式名称冲突

### ISSUE THREAD

**Issue by linsage** [skyvow/wux#17]
https://github.com/weui/weui-wxss

项目中使用了weui.wxss 与 wux 组件样式名称冲突

**Comment by Lxxyx** [comment]
建议添加更多信息。
同使用 weui-wxss 与 wux，没有样式冲突问题

**Comment by skyvow** [comment]
@linsage @Lxxyx 感谢反馈，2.0 已修复。
