### ISSUE TITLE
component的事件调用

### ISSUE THREAD

**Issue by BoleLee** [skyvow/wux#27]
`Component`类的数据是通过加前缀`$wux.componentname.examplename`插入到Page中的，但是事件是怎么插入我不是很明白， @skyvow 可否说明下，谢谢赐教～

**Comment by skyvow** [comment]
`/**
     * 绑定组件事件函数
     */
    __initMethods() {
        const scope = this.options.scope
        const methods = this.options.methods

        // 筛选函数类型
        if (!this.isEmptyObject(methods)) {
            for (let key in methods) {
                if (methods.hasOwnProperty(key) && typeof methods[key] === `function`) {
                    this[key] = methods[key] = methods[key].bind(this)

                    // 将 methods 内的方法重命名并挂载到 page 上面，否则 template 内找不到事件
                    this.page[`${scope}.${key}`] = methods[key]

                    // 将方法名同步至 page.data 上面，方便在模板内使用 {{ method }} 方式绑定事件
                    this.setData({
                        [`${scope}.${key}`]: `${scope}.${key}`,
                    })
                }
            }
        }
    }`
