### ISSUE TITLE
#Rater组件的使用问题 "如何给一个列表传不同的评分(value)?"

### ISSUE THREAD

**Issue by SIGAOYI** [skyvow/wux#28]
个人学习的时候遇到问题,此处的value如何给列表中多个星星?
场景页面:评价列表,一个列表里有多个评分和星星.
如何给每行item赋各自不同的value?

`onLoad() {
    $wuxRater.init('decimal', {
    value: 3.7,
    disabled: !0,
    })
  },`

**Comment by skyvow** [comment]
@SIGAOYI 看 demo 例子

**Comment by SIGAOYI** [comment]
谢谢！已解决
