### ISSUE TITLE
多次new Component实例的问题

### ISSUE THREAD

**Issue by luoyunjiao** [skyvow/wux#3]
showToast() {
		this.$wuxToast.show({
			type: 'success',
			timer: 1500,
			color: '#fff',
			text: '已完成',
			success: () => console.log('已完成')
		})
	},
	showToastCancel() {
		this.$wuxToast.show({
			type: 'cancel',
			timer: 1500,
			color: '#fff',
			text: '取消操作',
			success: () => console.log('取消操作')
		})
	}

比如pages里面的toast示例，其实每次show都会new一个component实例，从性能上考虑有木有更好的办法？:)

**Comment by skyvow** [comment]
我有考虑过，可是还没想到好的方法，你有什么好意见嘛？

**Comment by ZinCode** [comment]
作者想到什么好办法了吗？

**Comment by GerryLon** [comment]
使用单例?
