### ISSUE TITLE
报错 firstRender not the data from Page.data

### ISSUE THREAD

**Issue by 66beta** [skyvow/wux#30]
$wui.xxx.yyy这类都是onload之后才挂到Page的data上的，所以页面初始化时候没有这类数据
`<template data="...$wui.xxx.yyy"`就报错

目前只找到笨办法手动提前设置好
```
Page({
  data: {
    $wui: { xxx: { yyy: [] } }
  }
})
```

**Comment by skyvow** [comment]
@66beta :joy: 笨办法也很好用
