### ISSUE TITLE
能不能增加一个下拉筛选的菜单组件

### ISSUE THREAD

**Issue by sonicsunsky** [skyvow/wux#36]
网上有一些下拉筛选的菜单组件感觉不是太好，看到大神的组件封装得逼格很高，可否有时间新增一个功能比较齐全的下拉筛选菜单组件？

**Comment by skyvow** [comment]
@sonicsunsky 最新版已加入该功能，欢迎试用。

**Comment by sonicsunsky** [comment]
@skyvow 嗯，已经开始使用，效果很好，大神辛苦了，多谢多谢
