### ISSUE TITLE
不是issue

### ISSUE THREAD

**Issue by xxxman2008** [skyvow/wux#37]
你做的 这个组件，效果很漂亮。大赞，帮了我这个后端大忙。

通常，这个时候，会有一个但是。。。
但是，编程风格上面，我这个后端程序员就很痛苦了。。而且文档说明也不多，幸好有很多例子，而且还是特新潮的 ES6 的 例子。。老人家看起来很累啊，很累啊，很累啊，很累啊。。

**Comment by skyvow** [comment]
@xxxman2008 感谢支持，这样想想借此机会还可以学习啊，有什么不明白的也可以直接找我。
