### ISSUE TITLE
filterbar筛选在模拟器可以使用，到真机上层级出现问题，弹出层在list下面

### ISSUE THREAD

**Issue by wangpengzong** [skyvow/wux#40]
如题

**Comment by skyvow** [comment]
@wangpengzong 请提供一下操作系统版本、微信的版本

**Comment by wangpengzong** [comment]
windows 10 专业版

**Comment by wangpengzong** [comment]
windows 10 专业版
微信开发工具 v1.02.1801081    模拟器  iphone 5  微信  iphone 5s,6s  6.6.1

**Comment by wangpengzong** [comment]
@skyvow

**Comment by skyvow** [comment]
@wangpengzong 试了一下 iphone 6s 未重现，有没有更改过层级样式或者其他的影响到 filterbar 组件呢？
