### ISSUE TITLE
qrcode

### ISSUE THREAD

**Issue by sanshengs** [skyvow/wux#42]
请问QRCODE模块，为什么开发者工具重新编译就报错，关闭项目重新打开又正常？

**Comment by skyvow** [comment]
@sanshengs 请提供工具版本，且如何复现呢？

**Comment by sanshengs** [comment]
@skyvow  开发工具版本v1.02.1801081, 第一次启动成功，在任意注释处修改 重新编译，报错typeerror illegal invocation

**Comment by skyvow** [comment]
@sanshengs 尝试复现了并没有出现报错

**Comment by sanshengs** [comment]
@skyvow 谢谢,我自己再测试
