### ISSUE TITLE
编译不过！Error: ENOENT: no such file or directory, open 'E:\Proj\view_component\wux\dist\game.json’

### ISSUE THREAD

**Issue by QQ565253906** [skyvow/wux#43]
![image](https://user-images.githubusercontent.com/24185552/35338378-ba57c242-0158-11e8-92b1-a3d10ae38b40.png)
请问上面这个error是怎么回事，有点莫名其妙

**Comment by skyvow** [comment]
@QQ565253906 game.json 哪里来的，删掉试试
