### ISSUE TITLE
筛选框一级的时候，类型为checkbox，子级别的value无效

### ISSUE THREAD

**Issue by robogame** [skyvow/wux#47]
感谢作者的辛勤劳动，做出这么好的产品。
现在有个问题，就是在筛选框为一级的时候，类型选择为checkbox，子级别的value无效，二级筛选框没问题。

![1](https://user-images.githubusercontent.com/3633196/35605481-e389f51a-0683-11e8-8bc3-b17b90555ba9.jpg)
![2](https://user-images.githubusercontent.com/3633196/35605482-e3ba571e-0683-11e8-8171-33156f4618d5.jpg)

**Comment by robogame** [comment]
components/filterbar/filterbar.wxml的第70行
<view class="wux-cell__bd">{{ item.label }}</view>改为
<view class="wux-cell__bd">{{ p.label }}</view>即可

**Comment by skyvow** [comment]
@robogame 谢谢
