### ISSUE TITLE
filterbar侧边栏滚动影响蒙板后列表的滚动

### ISSUE THREAD

**Issue by Goldman614** [skyvow/wux#53]
filterbar组件弹出的筛选侧边栏，滑动时，蒙版后面的列表也跟着滚动，有什么办法能避免吗？
如以下Gif动图效果所示。
![1521687151057](https://user-images.githubusercontent.com/37645848/37748618-7613d434-2dbf-11e8-88cb-999e055aef9a.gif)

**Comment by Goldman614** [comment]
上滑到顶，下滑到底都会带动下方列表跟着滚动。

**Comment by qingfengmy** [comment]
The same problem as you
