### ISSUE TITLE
Error: Expect START descriptor with depth 2 but get another

### ISSUE THREAD

**Issue by lllito** [skyvow/wux#63]
console.group("Sat Apr 28 2018 16:38:10 GMT+0800 (CST) 渲染层错误")
console.error(`Error: Expect START descriptor with depth 2 but get another`)
console.groupEnd()
在使用dialog组件的时候 提示 如上错误。

**Comment by skyvow** [comment]
@lllito 请提供相关操作系统、开发者工具版本，且如何复现
