### ISSUE TITLE
calendar bug

### ISSUE THREAD

**Issue by wangsdragon** [skyvow/wux#9]
![image](https://user-images.githubusercontent.com/16381596/27377570-e85a8bf4-56a7-11e7-9dff-99a32b2004f7.png)
calendar组件逻辑有问题，运行源代码，显示如上图，主要调整下面地方，已可正常运行
updateMonths(offset, update) {
        if (!update) {
            return false
        }

		if (offset === `next`) {
			// const next = this._data.months[this._data.months.length - 1]
			// const nextDateTime = this.getNextDateTime(next.year, next.month)
            const currentYear = this._data.currentYear
            const currentMonth = this._data.currentMonth
			const currentDateTime = new Date(currentYear, currentMonth)
            const prevMonthHTML = this.monthHTML(currentDateTime, `prev`)
            const currentMonthHTML = this.monthHTML(currentDateTime)
            const nextMonthHTML = this.monthHTML(currentDateTime, `next`)
			// this._data.months.splice(0, 1)
			// this._data.months.push(nextMonthHTML)
            this._data.months = [prevMonthHTML, currentMonthHTML, nextMonthHTML]
		}

		if (offset === `prev`) {
			// const prev = this._data.months[0]
			// const prevDateTime = this.getPrevDateTime(prev.year, prev.month)
            const currentYear = this._data.currentYear
            const currentMonth = this._data.currentMonth
			const currentDateTime = new Date(currentYear, currentMonth-2)
            const prevMonthHTML = this.monthHTML(currentDateTime, `prev`)
            const currentMonthHTML = this.monthHTML(currentDateTime)
            const nextMonthHTML = this.monthHTML(currentDateTime, `next`)
			// this._data.months.splice(this._data.months.length - 1, 1)
			// this._data.months.unshift(prevMonthHTML)
            this._data.months = [prevMonthHTML, currentMonthHTML, nextMonthHTML]
		}
	}

**Comment by skyvow** [comment]
我试了一下，貌似不对呀。。。
